<?php

// database/seeders/VehicleSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use Faker\Factory as Faker;

class VehicleTableSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create();

        $brand = ['Kia', 'Mercedes', 'DS', 'Audi', 'Peugeot'];
        $model = ['xCeed', 'CLA', 'DS7', 'A4', '206'];
        $version = ['1.0 T-GDi Tech', '250e AMG', 'Crossback e-tense', 'Bussiness', 'sw'];
        $year = [2022, 2021, 2021, 2017, 2005];
        for ($i = 0; $i < 5; $i++) {
            Vehicle::create([
                'reference' => $faker->uuid,
                'brand' => $brand[$i],
                'model' => $model[$i],
                'version' => $version[$i],
                'year' => $year[$i],
                'sold' => false,
                'sale_date' => null,
                'kilometers' => $faker->numberBetween(1000, 200000),
                'power' => $faker->numberBetween(50, 300),
                'cylinder_capacity' => $faker->numberBetween(800, 5000),
                'consigned_vehicle' => $faker->boolean,
                'fuel' => $faker->randomElement(['Gasolina', 'Diesel', 'Elétrico', 'Híbrido']),
                'purchase_type' => $faker->randomElement(['Margem', 'Geral', 'Sem Iva']),
                'purchase_date' => $faker->date(),
                'purchase_price' => $faker->numberBetween(1000, 50000),
                'sell_price' => $faker->numberBetween(50000, 60000),
                'business_type' => $faker->randomElement(['novo', 'usado', 'seminovo']),
                'vin' => $faker->uuid,
                'manufacture_date' => $faker->date(),
                'register_date' => $faker->date(),
                'available_to_sell_date' => $faker->date(),
                'registration' => $faker->word,
                'segment' => $faker->word,
                'color' => $faker->safeColorName,
                'locality' => $faker->city,
                'observation' => $faker->sentence,
                'guarantee' => $faker->randomElement(['sem', '12 meses', '18 meses', '24 meses', '36 meses']),
                'guarantee_kms' => $faker->numberBetween(10000, 150000),
                'guarantee_brand' => $faker->date(),
                'inspection_until' => $faker->date(),
                'number_registrations' => $faker->numberBetween(1, 10),
                'origin' => $faker->randomElement(['importado', 'nacional']),
                'complete_review_book' => $faker->boolean,
                'second_key' => $faker->boolean,
                'non_smoker' => $faker->boolean,
                'supplier_id' => $faker->numberBetween(1, 10),
                'box_type' => $faker->randomElement(['manual', 'auto', 'semi']),
                'changes_number' => $faker->numberBetween(1, 5),
                'door_number' => $faker->numberBetween(2, 5),
                'capacity' => $faker->numberBetween(2, 8),
                'traction' => $faker->word,
                'autonomy' => $faker->randomNumber(),
                'co2' => $faker->randomFloat(2, 50, 300),
                'iuc' => $faker->randomFloat(2, 10, 500),
                'roof_racks' => $faker->boolean,
                'tow_hook' => $faker->boolean,
                'light_wheels' => $faker->boolean,
                'size_wheels' => $faker->numberBetween(15, 22),
                'fog_lights' => $faker->boolean,
                'directional_lights' => $faker->boolean,
                'daytime_running_lights' => $faker->boolean,
                'height_adjustable_lights' => $faker->boolean,
                'xenon_head_lights' => $faker->boolean,
                'bixenon_head_lights' => $faker->boolean,
                'headlights_with_brightness_sensor' => $faker->boolean,
                'led_front_headlights' => $faker->boolean,
                'led_rear_lights' => $faker->boolean,
                'full_led_headlights' => $faker->boolean,
                'heated_mirrors' => $faker->boolean,
                'electric_adjustable_mirrors' => $faker->boolean,
                'manual_adjustable_mirrors' => $faker->boolean,
                'auto_dimming_mirrors' => $faker->boolean,
                'power_folding_mirrors' => $faker->boolean,
                'front_power_windows' => $faker->boolean,
                'rear_power_windows' => $faker->boolean,
                'wood_steering_wheel' => $faker->boolean,
                'leather_steering_wheel' => $faker->boolean,
                'multifunction_steering_wheel' => $faker->boolean,
                'heated_multifunction_steering_wheel' => $faker->boolean,
                'steering_wheel_audio_controls' => $faker->boolean,
                'height_adjustable_steering_wheel' => $faker->boolean,
                'depth_adjustable_steering_wheel' => $faker->boolean,
                'electric_adjustable_steering_wheel' => $faker->boolean,
                'sunroof' => $faker->boolean,
                'fabric_seats' => $faker->boolean,
                'leather_seats' => $faker->boolean,
                'alcantara_seats' => $faker->boolean,
                'heated_seats' => $faker->boolean,
                'ventilated_seats' => $faker->boolean,
                'massage_seats' => $faker->boolean,
                'lumbar_support_seats' => $faker->boolean,
                'interior_color' => $faker->colorName,
                'armrest' => $faker->boolean,
                'heated_front_seats' => $faker->boolean,
                'front_seats_with_memory' => $faker->boolean,
                'electric_adjustable_front_seats' => $faker->boolean,
                'heated_rear_seats' => $faker->boolean,
                'individual_adjustable_rear_seats' => $faker->boolean,
                'rear_door_sunshades' => $faker->boolean,
                'rear_headrests' => $faker->boolean,
                'sport_seats' => $faker->boolean,
                'side_airbags' => $faker->boolean,
                'driver_airbag' => $faker->boolean,
                'passenger_airbag' => $faker->boolean,
                'safety_performance' => $faker->boolean,
                'alarm' => $faker->boolean,
                'isofix' => $faker->boolean,
                'immobilizer' => $faker->boolean,
                'electric_abs' => $faker->boolean,
                'power_steering' => $faker->boolean,
                'night_driving_assistance' => $faker->boolean,
                'electronic_differential_lock_eds' => $faker->boolean,
                'electronic_stability_control_esp' => $faker->boolean,
                'automatic_parking' => $faker->boolean,
                'automatic_door_lock_while_driving' => $faker->boolean,
                'torque_regulator_msr' => $faker->boolean,
                'hill_start_assist' => $faker->boolean,
                'individual_smart_key' => $faker->boolean,
                'tire_pressure_monitoring' => $faker->boolean,
                'sport_suspension' => $faker->boolean,
                'air_suspension' => $faker->boolean,
                'sport_package' => $faker->boolean,
                'start_stop_system' => $faker->boolean,
                'rain_sensors' => $faker->boolean,
                'parking_sensors' => $faker->boolean,
                'rearview_camera' => $faker->boolean,
                'central_locking_remote' => $faker->boolean,
                'mechanical_tuning' => $faker->boolean,
                'air_conditioning' => $faker->boolean,
                'usb_input' => $faker->boolean,
                'onboard_computer' => $faker->boolean,
                'cruise_control' => $faker->boolean,
                'hands_free_kit' => $faker->boolean,
                'automatic_tailgate' => $faker->boolean,
                'roof_screen' => $faker->boolean,
                'headrest_screen' => $faker->boolean,
                'center_console_screen' => $faker->boolean,
                'bluetooth' => $faker->boolean,
                'navigation_system_gps' => $faker->boolean,
                'usb_c' => $faker->boolean,
                'aux_input' => $faker->boolean,
                'sound_system' => $faker->boolean,
                'touchscreen' => $faker->boolean,
                'apple_carplay' => $faker->boolean,
                'keyless_entry' => $faker->boolean,
                'voice_control' => $faker->boolean,
                'rear_seat_usb' => $faker->boolean,
                'easy_open_close' => $faker->boolean,
                'virtual_cockpit' => $faker->boolean,
                'wireless_charging' => $faker->boolean,
            ]);
        }
    }
}
