<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\VehicleModel;
use App\Models\VehicleBrand;

class VehicleModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $models = [
            ['name' => 'MDX', 'reference' => 'A123', 'brand' => 'Acura'],
            ['name' => 'TLX', 'reference' => 'A123', 'brand' => 'Acura'],
            ['name' => 'RDX', 'reference' => 'A123', 'brand' => 'Acura'],
            ['name' => 'ILX', 'reference' => 'A123', 'brand' => 'Acura'],
            ['name' => 'RLX', 'reference' => 'A123', 'brand' => 'Acura'],
            ['name' => 'Giulia', 'reference' => 'A124', 'brand' => 'Alfa Romeo'],
            ['name' => 'Stelvio', 'reference' => 'A124', 'brand' => 'Alfa Romeo'],
            ['name' => '4C', 'reference' => 'A124', 'brand' => 'Alfa Romeo'],
            ['name' => 'MiTo', 'reference' => 'A124', 'brand' => 'Alfa Romeo'],
            ['name' => 'Giulietta', 'reference' => 'A124', 'brand' => 'Alfa Romeo'],
            ['name' => 'A3', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'A4', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'A6', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'Q3', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'Q5', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'Q7', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'Q8', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'A8', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'TT', 'reference' => 'A125', 'brand' => 'Audi'],
            ['name' => 'X3', 'reference' => 'B126', 'brand' => 'BMW'],
            ['name' => 'X5', 'reference' => 'B126', 'brand' => 'BMW'],
            ['name' => 'X7', 'reference' => 'B126', 'brand' => 'BMW'],
            ['name' => '3 Series', 'reference' => 'B126', 'brand' => 'BMW'],
            ['name' => '5 Series', 'reference' => 'B126', 'brand' => 'BMW'],
            ['name' => '7 Series', 'reference' => 'B126', 'brand' => 'BMW'],
            ['name' => 'Z4', 'reference' => 'B126', 'brand' => 'BMW'],
            ['name' => 'M3', 'reference' => 'B126', 'brand' => 'BMW'],
            ['name' => 'Enclave', 'reference' => 'B127', 'brand' => 'Buick'],
            ['name' => 'LaCrosse', 'reference' => 'B127', 'brand' => 'Buick'],
            ['name' => 'Regal', 'reference' => 'B127', 'brand' => 'Buick'],
            ['name' => 'Encore', 'reference' => 'B127', 'brand' => 'Buick'],
            ['name' => 'Verano', 'reference' => 'B127', 'brand' => 'Buick'],
            ['name' => 'Escalade', 'reference' => 'C128', 'brand' => 'Cadillac'],
            ['name' => 'CT4', 'reference' => 'C128', 'brand' => 'Cadillac'],
            ['name' => 'CT5', 'reference' => 'C128', 'brand' => 'Cadillac'],
            ['name' => 'XT4', 'reference' => 'C128', 'brand' => 'Cadillac'],
            ['name' => 'XT5', 'reference' => 'C128', 'brand' => 'Cadillac'],
            ['name' => 'XT6', 'reference' => 'C128', 'brand' => 'Cadillac'],
            ['name' => 'Malibu', 'reference' => 'C129', 'brand' => 'Chevrolet'],
            ['name' => 'Cruze', 'reference' => 'C129', 'brand' => 'Chevrolet'],
            ['name' => 'Equinox', 'reference' => 'C129', 'brand' => 'Chevrolet'],
            ['name' => 'Traverse', 'reference' => 'C129', 'brand' => 'Chevrolet'],
            ['name' => 'Tahoe', 'reference' => 'C129', 'brand' => 'Chevrolet'],
            ['name' => 'Silverado', 'reference' => 'C129', 'brand' => 'Chevrolet'],
            ['name' => 'Blazer', 'reference' => 'C129', 'brand' => 'Chevrolet'],
            ['name' => 'Colorado', 'reference' => 'C129', 'brand' => 'Chevrolet'],
            ['name' => 'Pacifica', 'reference' => 'C130', 'brand' => 'Chrysler'],
            ['name' => 'Voyager', 'reference' => 'C130', 'brand' => 'Chrysler'],
            ['name' => '300', 'reference' => 'C130', 'brand' => 'Chrysler'],
            ['name' => 'Charger', 'reference' => 'D131', 'brand' => 'Dodge'],
            ['name' => 'Challenger', 'reference' => 'D131', 'brand' => 'Dodge'],
            ['name' => 'Durango', 'reference' => 'D131', 'brand' => 'Dodge'],
            ['name' => 'Journey', 'reference' => 'D131', 'brand' => 'Dodge'],
            ['name' => 'Ram', 'reference' => 'D131', 'brand' => 'Dodge'],
            ['name' => 'Fiesta', 'reference' => 'F132', 'brand' => 'Ford'],
            ['name' => 'Focus', 'reference' => 'F132', 'brand' => 'Ford'],
            ['name' => 'Mustang', 'reference' => 'F132', 'brand' => 'Ford'],
            ['name' => 'Explorer', 'reference' => 'F132', 'brand' => 'Ford'],
            ['name' => 'F-150', 'reference' => 'F132', 'brand' => 'Ford'],
            ['name' => 'Edge', 'reference' => 'F132', 'brand' => 'Ford'],
            ['name' => 'Fusion', 'reference' => 'F132', 'brand' => 'Ford'],
            ['name' => 'Expedition', 'reference' => 'F132', 'brand' => 'Ford'],
            ['name' => 'Sierra', 'reference' => 'G133', 'brand' => 'GMC'],
            ['name' => 'Yukon', 'reference' => 'G133', 'brand' => 'GMC'],
            ['name' => 'Acadia', 'reference' => 'G133', 'brand' => 'GMC'],
            ['name' => 'Canyon', 'reference' => 'G133', 'brand' => 'GMC'],
            ['name' => 'Civic', 'reference' => 'H134', 'brand' => 'Honda'],
            ['name' => 'Accord', 'reference' => 'H134', 'brand' => 'Honda'],
            ['name' => 'CR-V', 'reference' => 'H134', 'brand' => 'Honda'],
            ['name' => 'Pilot', 'reference' => 'H134', 'brand' => 'Honda'],
            ['name' => 'HR-V', 'reference' => 'H134', 'brand' => 'Honda'],
            ['name' => 'Insight', 'reference' => 'H134', 'brand' => 'Honda'],
            ['name' => 'Ridgeline', 'reference' => 'H134', 'brand' => 'Honda'],
            ['name' => 'Elantra', 'reference' => 'H135', 'brand' => 'Hyundai'],
            ['name' => 'Sonata', 'reference' => 'H135', 'brand' => 'Hyundai'],
            ['name' => 'Santa Fe', 'reference' => 'H135', 'brand' => 'Hyundai'],
            ['name' => 'Tucson', 'reference' => 'H135', 'brand' => 'Hyundai'],
            ['name' => 'Kona', 'reference' => 'H135', 'brand' => 'Hyundai'],
            ['name' => 'Palisade', 'reference' => 'H135', 'brand' => 'Hyundai'],
            ['name' => 'Ioniq', 'reference' => 'H135', 'brand' => 'Hyundai'],
            ['name' => 'Q50', 'reference' => 'I136', 'brand' => 'Infiniti'],
            ['name' => 'Q60', 'reference' => 'I136', 'brand' => 'Infiniti'],
            ['name' => 'QX50', 'reference' => 'I136', 'brand' => 'Infiniti'],
            ['name' => 'QX80', 'reference' => 'I136', 'brand' => 'Infiniti'],
            ['name' => 'F-Type', 'reference' => 'J137', 'brand' => 'Jaguar'],
            ['name' => 'XE', 'reference' => 'J137', 'brand' => 'Jaguar'],
            ['name' => 'XF', 'reference' => 'J137', 'brand' => 'Jaguar'],
            ['name' => 'F-Pace', 'reference' => 'J137', 'brand' => 'Jaguar'],
            ['name' => 'I-Pace', 'reference' => 'J137', 'brand' => 'Jaguar'],
            ['name' => 'Range Rover', 'reference' => 'J137', 'brand' => 'Land Rover'],
            ['name' => 'Discovery', 'reference' => 'J137', 'brand' => 'Land Rover'],
            ['name' => 'Defender', 'reference' => 'J137', 'brand' => 'Land Rover'],
            ['name' => 'E-Pace', 'reference' => 'J137', 'brand' => 'Land Rover'],
            ['name' => 'Velar', 'reference' => 'J137', 'brand' => 'Land Rover'],
            ['name' => 'XE', 'reference' => 'J138', 'brand' => 'Lexus'],
            ['name' => 'ES', 'reference' => 'J138', 'brand' => 'Lexus'],
            ['name' => 'RX', 'reference' => 'J138', 'brand' => 'Lexus'],
            ['name' => 'LX', 'reference' => 'J138', 'brand' => 'Lexus'],
            ['name' => 'NX', 'reference' => 'J138', 'brand' => 'Lexus'],
            ['name' => 'CT', 'reference' => 'J138', 'brand' => 'Lexus'],
            ['name' => 'NX', 'reference' => 'J138', 'brand' => 'Lexus'],
            ['name' => 'GX', 'reference' => 'J138', 'brand' => 'Lexus'],
            ['name' => 'A-Class', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'B-Class', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'C-Class', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'E-Class', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'S-Class', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'CLA', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'GLA', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'GLB', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'GLE', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'GLS', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'G-Class', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'EQC', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'SLS AMG', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'SL', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'AMG GT', 'reference' => 'M139', 'brand' => 'Mercedes-Benz'],
            ['name' => 'Picanto', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Rio', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Ceed', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'xCeed', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Sportage', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Seltos', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Niro', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Stinger', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Carnival', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Soul', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'K900', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'K5', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'Telluride', 'reference' => 'K141', 'brand' => 'Kia'],
            ['name' => 'DS 3 Crossback', 'reference' => 'D142', 'brand' => 'DS Automobiles'],
            ['name' => 'DS 4', 'reference' => 'D142', 'brand' => 'DS Automobiles'],
            ['name' => 'DS 7 Crossback', 'reference' => 'D142', 'brand' => 'DS Automobiles'],
            ['name' => 'DS 9', 'reference' => 'D142', 'brand' => 'DS Automobiles'],
            ['name' => 'DS 5', 'reference' => 'D142', 'brand' => 'DS Automobiles'],
        ];

        $i=0;
        foreach ($models as $model) {
            $i++;
            $brand = VehicleBrand::where('name', $model['brand'])->first();
            if ($brand) {
                VehicleModel::create([
                    'name' => $model['name'],
                    'reference' => $model['reference'].  $i,
                    'vehicle_brand_id' => $brand->id,
                ]);
            }
        }
    }
}
