<?php
// database/migrations/xxxx_xx_xx_create_vehicles_table.php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateVehiclesTable extends Migration
{
    public function up()
    {
        Schema::create('vehicles', function (Blueprint $table) {
            $table->id();
            $table->string('reference')->unique();
            $table->string('brand');
            $table->string('model');
            $table->string('version')->nullable();
            $table->string('year')->nullable();
            $table->integer('kilometers')->nullable();
            $table->integer('power')->nullable();
            $table->integer('cylinder_capacity')->nullable();
            $table->boolean('consigned_vehicle')->default(false);
            $table->enum('fuel', ['', 'Diesel', 'Gasolina', 'Elétrico', 'Hibrido-plug-in/Gasolina', 'Hibrido-plug-in/Diesel', 'Outro'])->nullable();
            $table->enum('purchase_type', ['', 'Margem', 'Geral', 'Sem Iva'])->nullable();
            $table->date('purchase_date')->nullable();
            $table->decimal('purchase_price', 10, 2)->nullable();
            $table->decimal('sell_price', 10, 2)->nullable();
            $table->boolean('sold')->default(false);
            $table->date('sale_date')->nullable();
            $table->enum('business_type', ['', 'Novo', 'Usado', 'Semi-novo'])->nullable();
            $table->string('vin')->unique();
            $table->date('manufacture_date')->nullable();
            $table->date('register_date')->nullable();
            $table->date('available_to_sell_date')->nullable();
            $table->string('registration')->nullable();
            $table->string('segment')->nullable();
            $table->string('color')->nullable();
            $table->string('locality')->nullable();
            $table->text('observation')->nullable();
            $table->enum('guarantee', ['Sem', '12 meses', '18 meses', '24 meses', '36 meses']);
            $table->integer('guarantee_kms')->nullable();
            $table->date('guarantee_brand')->nullable();
            $table->date('inspection_until')->nullable();
            $table->integer('number_registrations')->nullable();
            $table->enum('origin', ['', 'Importado', 'Nacional']);
            $table->boolean('complete_review_book')->default(false);
            $table->boolean('second_key')->default(false);
            $table->boolean('non_smoker')->default(false);
            $table->unsignedBigInteger('supplier_id')->nullable();
            $table->foreign('supplier_id')->references('id')->on('suppliers')->onDelete('set null');
            $table->enum('box_type', ['', 'Manual', 'Automático', 'Semi-Automático']);
            $table->integer('changes_number')->nullable();
            $table->integer('door_number')->nullable();
            $table->integer('capacity')->nullable();
            $table->string('traction')->nullable();
            $table->string('autonomy')->nullable();
            $table->integer('co2')->nullable();
            $table->decimal('iuc', 10, 2)->nullable();
            $table->boolean('roof_racks')->default(false);
            $table->boolean('tow_hook')->default(false);
            $table->boolean('light_wheels')->default(false);
            $table->integer('size_wheels')->nullable();
            $table->boolean('fog_lights')->default(false);
            $table->boolean('directional_lights')->default(false);
            $table->boolean('daytime_running_lights')->default(false);
            $table->boolean('height_adjustable_lights')->default(false);
            $table->boolean('xenon_head_lights')->default(false);
            $table->boolean('bixenon_head_lights')->default(false);
            $table->boolean('headlights_with_brightness_sensor')->default(false);
            $table->boolean('led_front_headlights')->default(false);
            $table->boolean('led_rear_lights')->default(false);
            $table->boolean('full_led_headlights')->default(false);
            $table->boolean('heated_mirrors')->default(false);
            $table->boolean('electric_adjustable_mirrors')->default(false);
            $table->boolean('manual_adjustable_mirrors')->default(false);
            $table->boolean('auto_dimming_mirrors')->default(false);
            $table->boolean('power_folding_mirrors')->default(false);
            $table->boolean('front_power_windows')->default(false);
            $table->boolean('rear_power_windows')->default(false);
            $table->boolean('wood_steering_wheel')->default(false);
            $table->boolean('leather_steering_wheel')->default(false);
            $table->boolean('multifunction_steering_wheel')->default(false);
            $table->boolean('heated_multifunction_steering_wheel')->default(false);
            $table->boolean('steering_wheel_audio_controls')->default(false);
            $table->boolean('height_adjustable_steering_wheel')->default(false);
            $table->boolean('depth_adjustable_steering_wheel')->default(false);
            $table->boolean('electric_adjustable_steering_wheel')->default(false);
            $table->boolean('sunroof')->default(false);
            $table->boolean('fabric_seats')->default(false);
            $table->boolean('leather_seats')->default(false);
            $table->boolean('alcantara_seats')->default(false);
            $table->boolean('heated_seats')->default(false);
            $table->boolean('ventilated_seats')->default(false);
            $table->boolean('massage_seats')->default(false);
            $table->boolean('lumbar_support_seats')->default(false);
            $table->string('interior_color')->default(false);
            $table->boolean('armrest')->default(false);
            $table->boolean('heated_front_seats')->default(false);
            $table->boolean('front_seats_with_memory')->default(false);
            $table->boolean('electric_adjustable_front_seats')->default(false);
            $table->boolean('heated_rear_seats')->default(false);
            $table->boolean('individual_adjustable_rear_seats')->default(false);
            $table->boolean('rear_door_sunshades')->default(false);
            $table->boolean('rear_headrests')->default(false);
            $table->boolean('sport_seats')->default(false);
            $table->boolean('side_airbags')->default(false);
            $table->boolean('driver_airbag')->default(false);
            $table->boolean('passenger_airbag')->default(false);
            $table->boolean('safety_performance')->default(false);
            $table->boolean('alarm')->default(false);
            $table->boolean('isofix')->default(false);
            $table->boolean('immobilizer')->default(false);
            $table->boolean('electric_abs')->default(false);
            $table->boolean('power_steering')->default(false);
            $table->boolean('night_driving_assistance')->default(false);
            $table->boolean('electronic_differential_lock_eds')->default(false);
            $table->boolean('electronic_stability_control_esp')->default(false);
            $table->boolean('automatic_parking')->default(false);
            $table->boolean('automatic_door_lock_while_driving')->default(false);
            $table->boolean('torque_regulator_msr')->default(false);
            $table->boolean('hill_start_assist')->default(false);
            $table->boolean('individual_smart_key')->default(false);
            $table->boolean('tire_pressure_monitoring')->default(false);
            $table->boolean('sport_suspension')->default(false);
            $table->boolean('air_suspension')->default(false);
            $table->boolean('sport_package')->default(false);
            $table->boolean('start_stop_system')->default(false);
            $table->boolean('rain_sensors')->default(false);
            $table->boolean('parking_sensors')->default(false);
            $table->boolean('rearview_camera')->default(false);
            $table->boolean('central_locking_remote')->default(false);
            $table->boolean('mechanical_tuning')->default(false);
            $table->boolean('air_conditioning')->default(false);
            $table->boolean('usb_input')->default(false);
            $table->boolean('onboard_computer')->default(false);
            $table->boolean('cruise_control')->default(false);
            $table->boolean('hands_free_kit')->default(false);
            $table->boolean('automatic_tailgate')->default(false);
            $table->boolean('roof_screen')->default(false);
            $table->boolean('headrest_screen')->default(false);
            $table->boolean('center_console_screen')->default(false);
            $table->boolean('bluetooth')->default(false);
            $table->boolean('navigation_system_gps')->default(false);
            $table->boolean('usb_c')->default(false);
            $table->boolean('aux_input')->default(false);
            $table->boolean('sound_system')->default(false);
            $table->boolean('touchscreen')->default(false);
            $table->boolean('apple_carplay')->default(false);
            $table->boolean('keyless_entry')->default(false);
            $table->boolean('voice_control')->default(false);
            $table->boolean('rear_seat_usb')->default(false);
            $table->boolean('easy_open_close')->default(false);
            $table->boolean('virtual_cockpit')->default(false);
            $table->boolean('wireless_charging')->default(false);
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('vehicles');
    }
}
